#:schema node_modules/wrangler/config-schema.json
name = "short-url"
main = "src/index.js"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
#route = "link.evertcode.dev/*"

kv_namespaces = [{ binding = "URLS", id = "5c8c9357a1574df6993782808e185220" }]

#vars = { AUTH_SECRET = "evertcodesecret" }
